### ISSUE TITLE
update container to support openssl 1.1.1 for arangodb builds after v3.5.1.1

### ISSUE THREAD

**Issue by c-nv-s** [arangodb-helper/build-docker-containers#4]
Is it possible to update the scripts so that openssl tooling version 1.1.1 is available within the containers for building?

It seems to fail when trying to build any version of arangodb after v3.5.1.1 due to this dependency.

**Comment by dothebart** [comment]
Hi, 
the ArangoDB binaries are meanwhile built via https://github.com/arangodb/oskar/ - which produce static binaries for alpine environments.

**Comment by c-nv-s** [comment]
> on

OK thanks for the info :-)
